/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtelierSuite9x4fRouteImport } from './routes/atelier-suite-9x4f'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AtelierSuite9x4fIndexRouteImport } from './routes/atelier-suite-9x4f.index'
import { Route as AtelierSuite9x4fDashboardRouteImport } from './routes/atelier-suite-9x4f.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierSuite9x4fRoute = AtelierSuite9x4fRouteImport.update({
  id: '/atelier-suite-9x4f',
  path: '/atelier-suite-9x4f',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierSuite9x4fIndexRoute = AtelierSuite9x4fIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtelierSuite9x4fRoute,
} as any)
const AtelierSuite9x4fDashboardRoute =
  AtelierSuite9x4fDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AtelierSuite9x4fRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier-suite-9x4f': typeof AtelierSuite9x4fRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/atelier-suite-9x4f/dashboard': typeof AtelierSuite9x4fDashboardRoute
  '/atelier-suite-9x4f/': typeof AtelierSuite9x4fIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/atelier-suite-9x4f/dashboard': typeof AtelierSuite9x4fDashboardRoute
  '/atelier-suite-9x4f': typeof AtelierSuite9x4fIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atelier-suite-9x4f': typeof AtelierSuite9x4fRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/atelier-suite-9x4f/dashboard': typeof AtelierSuite9x4fDashboardRoute
  '/atelier-suite-9x4f/': typeof AtelierSuite9x4fIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atelier-suite-9x4f'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/atelier-suite-9x4f/dashboard'
    | '/atelier-suite-9x4f/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/atelier-suite-9x4f/dashboard'
    | '/atelier-suite-9x4f'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atelier-suite-9x4f'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/atelier-suite-9x4f/dashboard'
    | '/atelier-suite-9x4f/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtelierSuite9x4fRoute: typeof AtelierSuite9x4fRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-suite-9x4f': {
      id: '/atelier-suite-9x4f'
      path: '/atelier-suite-9x4f'
      fullPath: '/atelier-suite-9x4f'
      preLoaderRoute: typeof AtelierSuite9x4fRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier-suite-9x4f/': {
      id: '/atelier-suite-9x4f/'
      path: '/'
      fullPath: '/atelier-suite-9x4f/'
      preLoaderRoute: typeof AtelierSuite9x4fIndexRouteImport
      parentRoute: typeof AtelierSuite9x4fRoute
    }
    '/atelier-suite-9x4f/dashboard': {
      id: '/atelier-suite-9x4f/dashboard'
      path: '/dashboard'
      fullPath: '/atelier-suite-9x4f/dashboard'
      preLoaderRoute: typeof AtelierSuite9x4fDashboardRouteImport
      parentRoute: typeof AtelierSuite9x4fRoute
    }
  }
}

interface AtelierSuite9x4fRouteChildren {
  AtelierSuite9x4fDashboardRoute: typeof AtelierSuite9x4fDashboardRoute
  AtelierSuite9x4fIndexRoute: typeof AtelierSuite9x4fIndexRoute
}

const AtelierSuite9x4fRouteChildren: AtelierSuite9x4fRouteChildren = {
  AtelierSuite9x4fDashboardRoute: AtelierSuite9x4fDashboardRoute,
  AtelierSuite9x4fIndexRoute: AtelierSuite9x4fIndexRoute,
}

const AtelierSuite9x4fRouteWithChildren =
  AtelierSuite9x4fRoute._addFileChildren(AtelierSuite9x4fRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtelierSuite9x4fRoute: AtelierSuite9x4fRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
